### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by khaffner** [BITPlan/can4eve#16]
Hello
I'm trying to use this software to get a report about my i-Miew.

According to the docs and reading some of the code, I thought this syntax should be correct:
`java -jar can4eve.jar --conn /dev/ttyUSB0 --baud 500000 --report report.csv`
 but i get the output
`Exception in thread "main" java.lang.NoClassDefFoundError: javafx/event/EventHandler
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at com.bitplan.obdii.OBDMain.work(OBDMain.java:391)
        at com.bitplan.javafx.Main.maininstance(Main.java:144)
        at com.bitplan.obdii.OBDMain.main(OBDMain.java:439)
Caused by: java.lang.ClassNotFoundException: javafx.event.EventHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 27 more`

(I'm not that familiar with Java.)

Just running
`java -jar can4eve.jar -h`
works fine, I get the help text.

My environment is Ubuntu 22.04, openjdk-8-jdk and an OBDLink SX.
I suspect I just got the parameters wrong.

Please let me know if you have any tips or answers :)

**Comment by WolfgangFahl** [comment]
thank you for trying out can4eve. JavaFx is needed as a prerequisite. Are you using a raspberry or other hardware? See https://stackoverflow.com/questions/36961054/can-javafx-be-used-on-raspberry-pi and my answer there for how to install.

**Comment by khaffner** [comment]
At the moment I'm using a laptop, but the plan was to use can4eve in a Docker container(on a Pi, but that might not be relevant then) after I get it working on the laptop. Thanks for the information about JavaFx, that should help me continue.

**Comment by khaffner** [comment]
Hello again.

I'm getting a headache trying to properly install javafx directly on my laptop, so I'm going straight to the Docker deployment which is the final destination in my case. I think I've managed to find an image with javafx (https://hub.docker.com/r/platpus/javafx), at least the error message now does not complain about javafx:
(edit: Might try https://hub.docker.com/r/odinuge/maven-javafx/dockerfile later, because it has documented Dockerfile.)
(edit: Also, the --device is not the same as before, this attempt was with an OBDLink LX(Bluetooth))

```console
kevin@t490:~$ docker run -it --device=/dev/rfcomm0:/dev/rfcomm0 test bash
root@82c692cf61a6:/app# java -jar /app/can4eve.jar --conn /dev/rfcomm0 --baud 500000 --report csv.csv
Jul 08, 2023 1:51:55 PM com.bitplan.error.ErrorHandler handle
WARNING: Error java.lang.UnsupportedOperationException:Unable to open DISPLAY
Jul 08, 2023 1:51:55 PM com.bitplan.error.ErrorHandler handle
WARNING: Stacktrace: java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.bitplan.javafx.WaitableApp.toolkitInit(WaitableApp.java:92)
	at com.bitplan.javafx.GenericApp.<init>(GenericApp.java:277)
	at com.bitplan.obdii.javafx.JavaFXDisplay.<init>(JavaFXDisplay.java:140)
	at com.bitplan.obdii.JFXTripletDisplay.<init>(JFXTripletDisplay.java:69)
	at com.bitplan.obdii.OBDMain.work(OBDMain.java:391)
	at com.bitplan.javafx.Main.maininstance(Main.java:144)
	at com.bitplan.obdii.OBDMain.main(OBDMain.java:439)
root@82c692cf61a6:/app#
```
Now DISPLAY seems to be an issue. Which makes sense, given that this is inside a container which has no displays. So I look at the help section:
```console
root@82c692cf61a6:/app# java -jar /app/can4eve.jar -h
Help
can4eve: 0.0.5

  usage: java can4eve
 --display [None | JavaFX]  : display
                              the display to use one of:
                               None,JavaFX (default: JavaFX)
```
Aha, the default is JavaFX. Let's just set this to None:
```console
root@82c692cf61a6:/app# java -jar /app/can4eve.jar --display None --conn /dev/rfcomm0 --baud 500000 --report csv.csv
Help
can4eve: 0.0.5

  usage: java can4eve
 --display [None | JavaFX]  : display
                              the display to use one of:
                               None,JavaFX (default: None)
```
That just shows me the help section again, but now the default is None...?

Am I doing something wrong? Can this tool be run completely headless without a display, using only the command line? 
Thanks :)
